
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('John.Smith@gmail.com', 'John Smith', 'Apt 100 SW Illini Ave');
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('Peter.Heins@gmail.com', 'Peter Heins', 'Apt 200 SW Illini Ave');

INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (100,'HEATING/COOLING');
INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (101,'APPLIANCES');

INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1000,100,'Randel Orton');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1000,101,'Randel Orton');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1001,100,'Mike Hussy');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1001,101,'Mike Hussy');

INSERT INTO TECHNICIAN_AVAILABILITY_STATUS (TECH_ID, TECH_HOLD_STATUS) VALUES (1000,'A');
INSERT INTO TECHNICIAN_AVAILABILITY_STATUS (TECH_ID, TECH_HOLD_STATUS) VALUES (1001,'A');

