
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('John.Smith@gmail.com', 'John Smith', 'Apt 100 SW Illini Ave');
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('Peter.Heins@gmail.com', 'Peter Heins', 'Apt 200 SW Illini Ave');
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('Jessica.Smith@gmail.com', 'Jessica Smith', 'Apt 300 SW Illini Ave');
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('Andrew.Whalley@gmail.com', 'Andrew Whalley', 'Apt 400 SW Illini Ave');
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('Srabani.Nayak@gmail.com', 'Srabani Nayak', 'Apt 500 SW Illini Ave');
INSERT INTO CUSTOMER (CUST_EMAIL, CUST_NAME, CUST_ADDRESS) VALUES ('Pradeep.Kumar@gmail.com', 'Pradeep Kumar', 'Apt 600 SW Illini Ave');



INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (100,'Heating/Cooling');
INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (101,'Appliances');
INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (121,'Building Window Washing');
INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (343,'Security Gaurd');
INSERT INTO CRITERIA (ISSUE_ID, ISSUE_TYPE) VALUES (565,'Delivery Service');


INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1000,100,'Randel Orton');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1000,101,'Randel Orton');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1001,101,'Mike Hussy');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1001,121,'Mike Hussy');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1001,343,'Mike Hussy');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1002,565,'Nathan Astle');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1003,100,'David Boon');
INSERT INTO TECHNICIAN (TECH_ID, TECH_CAPABILITY_ID,TECH_NAME) VALUES (1003,121,'David Boon');

INSERT INTO TECHNICIAN_AVAILABILITY_STATUS (TECH_ID, TECH_HOLD_STATUS) VALUES (1000,'A');
INSERT INTO TECHNICIAN_AVAILABILITY_STATUS (TECH_ID, TECH_HOLD_STATUS) VALUES (1001,'A');
INSERT INTO TECHNICIAN_AVAILABILITY_STATUS (TECH_ID, TECH_HOLD_STATUS) VALUES (1002,'A');
INSERT INTO TECHNICIAN_AVAILABILITY_STATUS (TECH_ID, TECH_HOLD_STATUS) VALUES (1003,'A');
